foreground #f6dcac
background #05182e
selection_foreground #f6dcac
selection_background #134e5a

cursor #f6dcac
cursor_text_color #05182e

active_border_color #faa968
active_tab_background #faa968

color0 #05182e
color1 #f85525
color2 #028391
color3 #e97b3c
color4 #3f8f8a
color5 #3f8f8a
color6 #8cbfb8
color7 #f6dcac
color8 #2a6b78
color9 #f85525
color10 #028391
color11 #e97b3c
color12 #faa968
color13 #3f8f8a
color14 #8cbfb8
color15 #f6dcac
