music_directory     "/home/root-0/music"
playlist_directory  "/home/root-0/music"
db_file             "/home/root-0/.local/state/mpd/database"
log_file            "/home/root-0/.local/state/mpd/mpd.log"
state_file          "/home/root-0/.local/state/mpd/state"
sticker_file        "/home/root-0/.local/state/mpd/sticker.sql"
pid_file            "/home/root-0/.local/state/mpd/pid"

bind_to_address     "127.0.0.1"
port                "6600"
bind_to_address     "/home/root-0/.local/state/mpd/socket"

audio_output {
    type    "pulse"
    name    "Pulse Output"
}

audio_output {
    type    "null"
    name    "Null Output"
}

filesystem_charset  "UTF-8"
auto_update         "yes"
